---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: aurora
# description will be included in the image's metadata
description: Aurora DX (Nvidia) with NordVPN, Bitwarden, Emacs, and other tweaks

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - download-bitwarden.sh

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - nordvpn.repo
    optfix:
      - Bitwarden
      - nordvpn-gui
    install:
      - micro
      - starship
      - emacs
      - emacsclient
      - vim
      - nordvpn-gui
      - bitwarden-latest.rpm

  - type: script
    snippets:
      - "rm /bitwarden-latest.rpm"
      - "ln -sf /usr/lib/opt/Bitwarden/bitwarden /etc/alternatives/bitwarden"

      # this `chcon` command is part of the script that a running Bitwarden
      # client executes when you tell it to integrate with system
      # authentication, but in the build process it results in an "operation not permitted" error:
      #
      #   chcon: failed to change context of '/usr/share/polkit-1/actions/com.bitwarden.Bitwarden.policy' to 'system_u:object_r:usr_t:s0': Operation not permitted
      #
      #- "chcon system_u:object_r:usr_t:s0 /usr/share/polkit-1/actions/com.bitwarden.Bitwarden.policy"

  - type: systemd
    system:
      enabled:
        - nordvpnd

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.notesnook.Notesnook
          - com.ticktick.TickTick
          - com.slack.Slack
          - com.discordapp.Discord
          #- com.valvesoftware.Steam
          #- net.lutris.Lutris
          #- info.mumble.Mumble
          #- io.github.pyfa_org.Pyfa
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

